@echo off
echo Starting Urtext Piano Development Environment...
echo.
echo Step 1: Building preload script...
call npm run build:preload
echo.
echo Step 2: Starting Vite dev server...
start "Vite Dev Server" cmd /k "npm run dev"
echo.
echo Step 3: Waiting for Vite to start...
timeout /t 5 /nobreak
echo.
echo Step 4: Starting Electron...
call npx electron .